#
# Symmetric Encryption for Ruby
#
---
# For the development and test environments the test symmetric encryption keys
# can be placed directly in the source code.
# And therefore no RSA private key is required
development:   &development_defaults
  key:         1234567890ABCDEF1234567890ABCDEF
  iv:          1234567890ABCDEF
  cipher_name: aes-128-cbc
  encoding:    :base64strict

test:
  <<: *development_defaults

release:
  # Since the key to encrypt and decrypt with must NOT be stored along with the
  # source code, we only hold a RSA key that is used to unlock the file
  # containing the actual symmetric encryption key
  private_rsa_key: |
    -----BEGIN RSA PRIVATE KEY-----
    MIIEogIBAAKCAQEAqGUzMuCB6O+xb8VxcrUETg1aqjR77krvV2mSaMPPYNtPgThL
    nE7sOKNB9Fiz6pblIGySaQqg6WWXmnzgyy4YgzYbcN/hzDCKqVBlNhTF1fqQZ/h9
    DMgY+zeZgn+bWSTHHz+Kud0/eHwhyCfAOAbFwgF+RZoDqR2OWATN2UNEeMznLUf1
    H0V5PIV2Tgm2gLUxOeZsHC3ECFoyQEAkfNv1AFBFysEh9+iDrzZihh0aEsVNurf8
    MASVM4rNWwFlCivwvC12uo9+a4u3L+WYcGmdpzOiWk/UGmaBbl6DoSXhprYyTE6l
    vgWtkdxoNR9DoXw1nIoan6RA1n7A3iNDgk3u7QIDAQABAoIBAH/8OoeGnvX9hyxe
    MjVuYxE3kRsfvLmF9pbHRGGfwTPqO2kI8l6glWUOoAgoisXXXdng6v4u99GsRydB
    llCWfkbrjruhTSo2Eo1Q7zvFWf+h6rM650AZrPLydRf8CIQeMcEMOFG/WIgoQDyy
    CaQLca5cGC6qOfIE5rT7IcDpIVd1mInLrh/Y8Y6bU8zxt0BY7/1Vmv8HgndOSvf5
    dbMW2GTgcTy2BDNb8Enk1OLHAqMmtzOgQJqxRMhAnKyS0Lt9NCA2DBwAFTvvB1U3
    QfcXiAyaeu+DB3reDFLaoMg1pGj0qq+imTxXjesiIfSIoZ6PTNcDufPnCvUhc6yG
    4fEbhHkCgYEA2t/qjhyMDMyUgjJk9VMwgzlOcxEs9/e6GufKFCGlCGcE4BSdqbtk
    owgrpbsg+L5Hfq5K+R7O7R6Ak/pqR+4Sje/DXRPV9SmhjaR4DKKXsKqDSfZbEr34
    gnPtwdKZfGt0M5DbMZ2laG3J2gNhyaXqmwrbDNSBPxPU13A6+cP/yd8CgYEAxPVY
    GUsIMfECxnz1OnXKFQnJAzSpWxLFEEWt3D0YFvXSg9Vew8+uA2Llc4k68tOlkP35
    7SsAGvlE3ybi4l0FpE9ZJfxjsx0dQ2UtLs66J5j6r5E0Ze3pYTXrpST+Pj1rz+Y3
    LtneL+6CDp4RcgKi0wUiow7B7/Imn6AzMG0VOLMCgYAHcAJ1b8zmhnEpd3LszzXf
    z6u1x0ii6H0feu7n/jiwb2fAAZNV+DM0QwvQpuo46aZeTKfpjT1020t9O84uwY1J
    23LlD85+dTqzKHqX21KSQ0kQ01lG6sOuEyhqJLDohHI/alW4euXrBYgNa34ALy4o
    tJa6+eGmdhMOexbV8+4WOwKBgBx/z8ahJ8dqM1ebPzS9VIdkyhRPq23FMoSfQIAM
    yw6PdW2kEzlMNMbCqablJYV7gIqRZXee8D328bNEgjH0+dsDrEel1JtXTCOzYS1T
    tnYCWcvLvAQ/v7RURAu6ZZuF8bK8giGiXtcasPECiE2x+fOE27UybneU12fjm2SX
    dCmnAoGAQ/EK442il6N8PlkcsjGJgH/lGleQ7ZY+Uj7dGUtIgDLB0cNZ0oV60yww
    ZJeO0J59AYmIeci0A5pRKqr2yx4pQs3ImyE2fEqGRDjMDGZ7WiP36++8zyOOSIb+
    /Eq1wtvkdV3gS0j4enI08Vu3NRLakSppwZpO4LuSGSNFrhPh4rQ=
    -----END RSA PRIVATE KEY-----


  # List Symmetric Key files in the order of current / latest first
  ciphers:
    -
      # Filename containing Symmetric Encryption Key encrypted using the
      # RSA public key derived from the private key above
      key_filename: /etc/rails/keys/imagegard_release.key
      iv_filename:  /etc/rails/keys/imagegard_release.iv
      cipher_name:  aes-256-cbc
      # Base64 encode encrypted data without newlines
      encoding:     :base64strict
      version:      1

production:
  # Since the key to encrypt and decrypt with must NOT be stored along with the
  # source code, we only hold a RSA key that is used to unlock the file
  # containing the actual symmetric encryption key
  private_rsa_key: |
    -----BEGIN RSA PRIVATE KEY-----
    MIIEpQIBAAKCAQEA1vljn9eB0IlUhWTaYxYygcL5UwQ17GM5ecPH8gCgoGf5Bkz6
    BtQtuxYT75ZTaouCPdyKz2kR8P7hGSRgLr8VpeQSK0LF/ayn4KXnVcHmA6mrUYNu
    v1tdE+WfwmX+cZ3qKwYZvchrtvREu6q7D2uEfXdemV2KIuArNe4G+lHhDkJbUulh
    HwNDBRABno/MHZ2HOOL8kKtmAEcJE8u1HXAxcLC+FP697fXRWKQx084oBibCjnW4
    u7CLE7Tkt+bEnSFlO3xjEkJ9HuKjAX0Kch2HMP+NS/BcnUTwOCbK6Jop/Ih26cJ4
    PdLVB1fo7p9VlHkM3oHE2aSbwhl25PeLVFhy4QIDAQABAoIBABCOHhz2JLohiU/I
    h4Tv9a3GjRrWjSyKK6fz6tb5M2WG/Ed+8BZMisUImzptMjlXSw1miY4Vglsz1bPw
    +DNBZfJjkP6h4st5W2hSfnE9QHBxxY6+d23nJFDe8yGuZxzq01jC3IKgB6OMRirJ
    qCQ03HwpEDDxYizzZIB/tyvZ2GIXl+6eJcnfeEteBMYYCyOeyacxOBhW909LpfYt
    lKBt2eG8FAoK1v6R9OWJXJFo3pTBhIlV+KpYd6fZk3bx0kxV+xqMzgvAor3Ql/xw
    3T3Dtr4Q0oOtLggHAUTZ/dVOpK0MauJli2LO+DfZ1wtX16cgevi88rJjDcpNvmli
    WHMbdd0CgYEA+AWd9FQBmK4iuq6r96yHkLufvzr3lUv8RHGHM9cFjzPeHmyTib2p
    Uhs0KdPnYF5qAZ94VFSLRq3eK5FPD/66yYGmSKzNFLAlOtokhcl9XcFLG55Qq3TG
    PoLwxA5P54lCz8NaSpuntsCR5U5dpLZutLgW9AMqHKnET+7/b1GIwLcCgYEA3eOi
    WAvRUVQfB4cA7uK1oCjQpCxPJcD5mRJJo09R0Hep54bLoHY/o/BGR98pryzHffyB
    1JYoxFs50geJFb7mdY4eGY51iPlZcQdL2oBNjwvNXtWo8D9RiRX6SnOaJkOJbCsa
    Okvex0uW2M5ro6FRZw02PpX4otY2lJ4t/GMwoScCgYEAwGPzC/UiK+JgVDlscjom
    CrJQD5HZPblsnVcHTsIrsNLGKQmGROGXd3Zct1mF8K4sQsgGGjxesVvrrBYSo1Cw
    aeElMNjCWJrutkFC9Xi/w7tN3MWow+dYZGNECoEjoHJMHkfmQVuO9GdahOqOH1fY
    dl0aiPvvbb6O5oZ5JEu17e8CgYEAhd/S0laG+w/LDOqaWIc2WCRoBbWqJzgwH/fV
    sA+qaCHaxBMjBnRx30KX1MNDTiqxTkUsPAxBGn+D+kGLpzAfseuGI5s9NOBk43oo
    fPOOV/Eh/sbgf9tkIVa+RW9MISv8XOQAlg2yowHrSHH6paYuDAP/p3Eqq2ydT7vE
    ORPLgl8CgYEA0m1OeipqNPL5w8182plTp8+9noGZgiaC/D9aOiItTGQVg5v2UprQ
    rF2Ze+mnmFjConurghNyQcqbzy+WEPYjSUZGOSsa/G4GHqZHkOxGGqlSuuNBCNUX
    5QK72Z1GaRQ+XNIfxbD5amQd6Nbnoa6AUrNJA4uRg5Dp3km2bncfumU=
    -----END RSA PRIVATE KEY-----


  # List Symmetric Key files in the order of current / latest first
  ciphers:
    -
      # Filename containing Symmetric Encryption Key encrypted using the
      # RSA public key derived from the private key above
      key_filename: /etc/rails/keys/imagegard_production.key
      iv_filename:  /etc/rails/keys/imagegard_production.iv
      cipher_name:  aes-256-cbc
      # Base64 encode encrypted data without newlines
      encoding:     :base64strict
      version:      1
